anime = ["HunterxHunter","Promised Neverland","My Hero Academia"]
anime.append("Dragon Ball")
print(anime)
shows = anime.copy()
print("Shows :",shows)
num = [1,2,2,3,4,8,9,91]
print(num)
print(num.count(2))
anime.extend(num)
print(anime)
print(num.index(2))
num.insert(5,5)
print(num)
num.pop(2)
print(num)
num.remove(91)
print(num)
num2 = [61,23,31,11,76,9]
num2.sort()
print(num2)
num2.sort(reverse=True)
print(num2)
anime.reverse()
print(anime)
anime.clear()
print(anime)